/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Code.DBConnect;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravindu Rathnagala
 */
public class AdminDoctorView extends javax.swing.JFrame {
 
    Connection con = null;
    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs=null;
    
    public AdminDoctorView() {
        initComponents();
        
        //connect to Db
        
        con =  (Connection) DBConnect.connect();
    }
    private void Reset()
    {
        txtName.setText("");
        txtNIC.setText("");
        boxSpc.setSelectedIndex(0);
        rbtn1.setSelected(false);
        rbtn2.setSelected(false); 
        pw.setText("");
        cpw.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availabilitygroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        boxSpc = new javax.swing.JComboBox<>();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        btnHome = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pw = new javax.swing.JPasswordField();
        cpw = new javax.swing.JPasswordField();
        chkbox1 = new javax.swing.JCheckBox();
        chkbox2 = new javax.swing.JCheckBox();
        btnHome1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("NIC                                        :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 200, 35));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Doctor Name                     :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 200, 35));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Speciality                            :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 200, 35));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Availability                         :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 200, 35));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 249, 35));

        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNICKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
        });
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 249, 35));

        boxSpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Speciality", "Primary Care", "Pediatrician", "Allergist", "Dermatologist", "Ophthalmologist", "Gynecologist", "Cardiologist.", "Endocrinologist", "Nephrologist", "Urologists", "Neurologist", "Psychiatrist", "Oncologist", "Radiologist", "Rheumatologist", "Orthopedic", " " }));
        jPanel1.add(boxSpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 249, 37));

        availabilitygroup.add(rbtn1);
        rbtn1.setText("Weekday");
        rbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(rbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 98, -1));

        availabilitygroup.add(rbtn2);
        rbtn2.setText("Weekend");
        jPanel1.add(rbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 98, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/home button-03.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 110, 40));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Password                             :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 200, 35));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Confirm Password             :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 200, 35));
        jPanel1.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 249, 35));
        jPanel1.add(cpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 249, 35));

        chkbox1.setText("Show");
        chkbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbox1ActionPerformed(evt);
            }
        });
        jPanel1.add(chkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 60, -1));

        chkbox2.setText("Show");
        chkbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbox2ActionPerformed(evt);
            }
        });
        jPanel1.add(chkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 60, -1));

        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/clear all button-03.png"))); // NOI18N
        btnHome1.setToolTipText("");
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 120, 40));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/update button-03.png"))); // NOI18N
        btnUpdate.setToolTipText("");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 110, 40));

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/delete button-03.png"))); // NOI18N
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 110, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/admin side bar-04.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 650));

        jPanel2.setBackground(new java.awt.Color(244, 239, 239));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 80, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor Management");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 640, 62));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
         AdminHome obj2 = new AdminHome();
        obj2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void chkbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbox1ActionPerformed
        if(chkbox1.isSelected()){
            pw.setEchoChar((char)0);
        }
        else{
            pw.setEchoChar('*');
        }
    }//GEN-LAST:event_chkbox1ActionPerformed

    private void chkbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbox2ActionPerformed
        if(chkbox2.isSelected()){
            cpw.setEchoChar((char)0);
        }
        else{
            cpw.setEchoChar('*');
        }
    }//GEN-LAST:event_chkbox2ActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        txtName.setText("");
        txtNIC.setText("");
        boxSpc.setSelectedIndex(0);
        rbtn1.setSelected(false);
        rbtn2.setSelected(false);
        pw.setText("");
        cpw.setText("");
        
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void rbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn1ActionPerformed
        
    }//GEN-LAST:event_rbtn1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
        
            String upnic = txtNIC.getText();
            String availability = "";
            if (rbtn1.isSelected()){
            
            availability = "Weekday";
        }
        else if(rbtn2.isSelected()){
            
            availability = "Weekend";
        }
            String p1 = "UPDATE doctor SET DoctorName=?,Speciality=?,Availability=?,DocPassword=?,DocCPassword=? WHERE DoctorNIC ='"+upnic+"' ";
            pst = con.prepareStatement(p1);
            pst.setString(1, txtName.getText());
            pst.setString(2, (String) boxSpc.getSelectedItem());
            pst.setString(3, availability);
            pst.setString(4, pw.getText());
            pst.setString(5, cpw.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Doctor Updated Successfully");
                
                Reset();
            
        } catch (SQLException ex) {
            Logger.getLogger(DrugsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased
       
    }//GEN-LAST:event_txtNICKeyReleased

    private void txtNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              try{
               String getId = txtNIC.getText();
               String q2 = "SELECT * from doctor WHERE DoctorNIC=?";
               pst = con.prepareStatement(q2);
               pst.setString(1, getId);
               rs = pst.executeQuery();
               
               if(rs.next()== false){
                 JOptionPane.showMessageDialog(this, "Doctor Id not found!","Message",JOptionPane.ERROR_MESSAGE);  
        
               }
               else{
                   String dname = rs.getString("DoctorName");
                   txtName.setText(dname.trim());
                   
                   String Spc = rs.getString("Speciality");
                   boxSpc.setSelectedItem(Spc.trim());
                   
                   String avail = rs.getString("Availability");
                   if(avail.equals("Weekday")){
                       rbtn1.setSelected(true);
                   }
        
                   else if(avail.equals("Weekend")){
                       rbtn2.setSelected(true);
                   }
                   
                   String pwd = rs.getString("DocPassword");
                   pw.setText(pwd.trim());
                   
                   String cpwd = rs.getString("DocCPassword");
                   cpw.setText(cpwd.trim());
  
               }
              
               
               
           }catch(Exception e){
               
           }
        }
    }//GEN-LAST:event_txtNICKeyPressed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try {
            
            String qd = "DELETE from doctor WHERE DoctorNIC=? ";
            pst = con.prepareStatement(qd);
            pst.setString(1,txtNIC.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully!!!");
            
            Reset();
            
        } catch (SQLException ex) {
            
        }
          
    }//GEN-LAST:event_btnDelActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        AdminHome a1 = new AdminHome();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDoctorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDoctorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup availabilitygroup;
    private javax.swing.JComboBox<String> boxSpc;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkbox1;
    private javax.swing.JCheckBox chkbox2;
    private javax.swing.JPasswordField cpw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pw;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
