/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;


import Code.DBConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;




public class AppointmentView extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
        
    public void Autogen(){
        try{
        Statement stmt = con.createStatement();
        String q1 = "select Max(AppointmentID) from appointments";
        
         ResultSet rs=stmt.executeQuery(q1);
            rs.next();
            
            rs.getString("Max(AppointmentID)");
            
            if(rs.getString("Max(AppointmentID)")==null){
                lblID.setText("A0001");
            }
            else{
                Long id = Long.valueOf(rs.getString("Max(AppointmentID)").substring(2,rs.getString("Max(AppointmentID)").length()));
                id++;
                lblID.setText("A0" + String.format("%03d",id));
            }
                
                } catch (SQLException ex) {
                 
        }
        } 
    
    public AppointmentView() {
        initComponents();
        con =  (Connection) DBConnect.connect();
        
         Autogen();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtContno = new javax.swing.JTextField();
        boxSpc = new javax.swing.JComboBox<>();
        btnchkdoccheck = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtDocName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        boxSpc1 = new javax.swing.JComboBox<>();
        btnHome2 = new javax.swing.JButton();
        btnHome3 = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Appointment ID                     :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 220, 35));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Patient Name                         :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 220, 35));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 230, 35));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Age                                            :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 220, 35));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Gender                                     :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 220, 35));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Address                                    :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 220, 35));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Contact no                              :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 220, 35));
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 230, 35));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 230, 70));
        jPanel1.add(txtContno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 230, 35));

        boxSpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        jPanel1.add(boxSpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 230, 37));

        btnchkdoccheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Check Doctor Availability button-03.png"))); // NOI18N
        btnchkdoccheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchkdoccheckActionPerformed(evt);
            }
        });
        jPanel1.add(btnchkdoccheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 410, 140, 50));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Doctor Name                         :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 220, 35));
        jPanel1.add(txtDocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 230, 35));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("Time                                        :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 220, 35));

        boxSpc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Time", "Weekday", "Weekend" }));
        jPanel1.add(boxSpc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 230, 37));

        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/home button-03.png"))); // NOI18N
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 110, 37));

        btnHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/clear all button-03.png"))); // NOI18N
        btnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 120, 37));

        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/print button-03.png"))); // NOI18N
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 100, 37));

        lblID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblIDPropertyChange(evt);
            }
        });
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 230, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/receptionist side bar-04.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 650));

        jPanel2.setBackground(new java.awt.Color(244, 239, 239));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 80, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Appointments");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 440, 56));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchkdoccheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchkdoccheckActionPerformed
        DoctorAvailabilityView d1 = new DoctorAvailabilityView();
        d1.setVisible(true);
        
    }//GEN-LAST:event_btnchkdoccheckActionPerformed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
        loginHome obj2 = new loginHome();
        obj2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome2ActionPerformed

    private void btnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome3ActionPerformed
       Autogen();
       txtName.setText("");
       txtAge.setText("");
       boxSpc.setSelectedIndex(0);
       txtAddress.setText("");
       txtContno.setText("");
       txtDocName.setText("");
       boxSpc1.setSelectedIndex(0);

    }//GEN-LAST:event_btnHome3ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        String Id = lblID.getText();
        String Pname = txtName.getText();
        String age = txtAge.getText();
        String gender = boxSpc.getSelectedItem().toString();
        String address = txtAddress.getText();
        String contactno = txtContno.getText();
        String DocName = txtDocName.getText();
        String time = boxSpc1.getSelectedItem().toString();
        
        try{
            if(Id.equals("")){
                JOptionPane.showMessageDialog(this, "Please generate an ID!","Message",JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(Pname.equals("")){
                    JOptionPane.showMessageDialog(this, "Please Fill out Name!","Message",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(age.equals("")){
                        JOptionPane.showMessageDialog(this, "Please Fill out Age!","Message",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        if(gender.equals("")){
                            JOptionPane.showMessageDialog(this, "Please select Gender!","Message",JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            if(address.equals("")){
                                JOptionPane.showMessageDialog(this, "Please Select Gender!","Message",JOptionPane.ERROR_MESSAGE);
                            }
                            else{
                                if(contactno.equals("")){
                                    JOptionPane.showMessageDialog(this, "Please Fill out Contact Number!","Message",JOptionPane.ERROR_MESSAGE);
                                }
                                else{
                                    if(DocName.equals("")){
                                        JOptionPane.showMessageDialog(this, "Please Fill out Doctor Name!","Message",JOptionPane.ERROR_MESSAGE);
                                    }
                                    else{
                                        if(time.equals("")){
                                          JOptionPane.showMessageDialog(this, "Please Fill out Time!","Message",JOptionPane.ERROR_MESSAGE);
                                        }
                                        else{
                                           String q = "INSERT INTO appointments(AppointmentID,PatientName,Age,Gender,Address,ContactNo,DoctorName,Time) values('" + Id + "' , '" + Pname+ "','" + age+ "','" +gender + "','"+ address +" ','" + contactno +"','" + DocName + "','"+time+"' )";
                                           pst = con.prepareStatement(q);
                                           pst.execute(); 
                                           
                                           JOptionPane.showMessageDialog(this, "Appointment created Successfully!");
                                           
                                             txtName.setText("");
                                             txtAge.setText("");
                                              boxSpc.setSelectedIndex(0);
                                              txtAddress.setText("");
                                              txtContno.setText("");
                                              txtDocName.setText("");
                                              boxSpc1.setSelectedIndex(0);
                                              
                                              Autogen();
                                              
                                           
                                           
                                        }
                                           
                                    }
                                }
                            }
                        }
                    }
                }
               
            }
            
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnprintActionPerformed

    private void lblIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblIDPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIDPropertyChange

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        loginHome a1 = new loginHome();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxSpc;
    private javax.swing.JComboBox<String> boxSpc1;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnHome3;
    private javax.swing.JButton btnchkdoccheck;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContno;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}

