/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Code.DBConnect;
import java.sql.*;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravindu Rathnagala
 */
public class DoctorRegistraionView extends javax.swing.JFrame {
 
    Connection con = null;
    PreparedStatement pst = null;
    
    public DoctorRegistraionView() {
        initComponents();
        
        //connect to Db
        
        con =  (Connection) DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availabilitygroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        boxSpc = new javax.swing.JComboBox<>();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        btnHome = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pw = new javax.swing.JPasswordField();
        cpw = new javax.swing.JPasswordField();
        chkbox1 = new javax.swing.JCheckBox();
        chkbox2 = new javax.swing.JCheckBox();
        btnHome1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("NIC                                        :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 200, 35));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Doctor Name                     :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 200, 35));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Speciality                            :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 200, 35));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Availability                         :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 200, 35));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 249, 35));
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 249, 35));

        boxSpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Speciality", "Primary Care", "Pediatrician", "Allergist", "Dermatologist", "Ophthalmologist", "Gynecologist", "Cardiologist.", "Endocrinologist", "Nephrologist", "Urologists", "Neurologist", "Psychiatrist", "Oncologist", "Radiologist", "Rheumatologist", "Orthopedic", " " }));
        jPanel1.add(boxSpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 249, 37));

        availabilitygroup.add(rbtn1);
        rbtn1.setText("Weekday");
        rbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(rbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 98, -1));

        availabilitygroup.add(rbtn2);
        rbtn2.setText("Weekend");
        jPanel1.add(rbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 98, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/home button-03.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 110, 37));

        btncreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/create button-03.png"))); // NOI18N
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel1.add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 110, 37));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Password                             :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 200, 35));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Confirm Password             :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 200, 35));
        jPanel1.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 249, 35));
        jPanel1.add(cpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 249, 35));

        chkbox1.setText("Show");
        chkbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbox1ActionPerformed(evt);
            }
        });
        jPanel1.add(chkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 85, -1));

        chkbox2.setText("Show");
        chkbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbox2ActionPerformed(evt);
            }
        });
        jPanel1.add(chkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 85, -1));

        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/clear all button-03.png"))); // NOI18N
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 120, 37));

        jLabel2.setText("Already Registered?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 124, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/login here button-03.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 140, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/doctor side bar-04.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 650));

        jPanel2.setBackground(new java.awt.Color(244, 239, 239));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 80, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor Registration");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 590, 56));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        loginHome obj1 = new loginHome();
        obj1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        
        String name = txtName.getText();
        String nic = txtNIC.getText();
        String speciality = boxSpc.getSelectedItem().toString();
        String availability = "";
        String password = pw.getText();
        String conPassword = cpw.getText();
        
        if (rbtn1.isSelected()){
            
            availability = "Weekday";
        }
        else if(rbtn2.isSelected()){
            
            availability = "Weekend";
        }
        try{
            if(txtName.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please Fill out Name!","Message",JOptionPane.ERROR_MESSAGE);
            }else{
                
            if(txtNIC.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please Fill out NIC!","Message",JOptionPane.ERROR_MESSAGE);
            }
            else{
                
                if(boxSpc.getSelectedItem().toString().equals("Select Speciality")){
                   JOptionPane.showMessageDialog(this, "Please Pick Your Speciality!","Message",JOptionPane.ERROR_MESSAGE); 
                }
                else{
            
               if(pw.getText().equals("")) {
                   JOptionPane.showMessageDialog(this, "Please fill out Password!","Message",JOptionPane.ERROR_MESSAGE); 
               }  
               else{
                   
               if(cpw.getText().equals("")){
                   JOptionPane.showMessageDialog(this, "Please Confirm previous Password!","Message",JOptionPane.ERROR_MESSAGE); 
               }
               else{
                   
               
            if(password.equals(conPassword)){
               
            
        String q = "INSERT INTO doctor (DoctorName,DoctorNIC,Speciality,Availability,DocPassword,DocCPassword) values('" + name + "' , '" + nic+ "','" + speciality+ "','" + availability + "','"+ password +" ','" + conPassword +"' )";
        pst = con.prepareStatement(q);
        pst.execute();
            
            txtName.setText("");
            txtNIC.setText("");
            boxSpc.setSelectedIndex(0);
            rbtn1.setSelected(false);
            rbtn2.setSelected(false);
            pw.setText("");
            cpw.setText("");
        
            JOptionPane.showMessageDialog(this, "Doctor Registered Successfully");
            }
                    else{
                JOptionPane.showMessageDialog(this, "The Passwords you entered are different","Message",JOptionPane.ERROR_MESSAGE);
                        }
                    }
                 }
                 } 
            }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Doctor Registeration Failed","Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void chkbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbox1ActionPerformed
        if(chkbox1.isSelected()){
            pw.setEchoChar((char)0);
        }
        else{
            pw.setEchoChar('*');
        }
    }//GEN-LAST:event_chkbox1ActionPerformed

    private void chkbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbox2ActionPerformed
        if(chkbox2.isSelected()){
            cpw.setEchoChar((char)0);
        }
        else{
            cpw.setEchoChar('*');
        }
    }//GEN-LAST:event_chkbox2ActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        txtName.setText("");
        txtNIC.setText("");
        boxSpc.setSelectedIndex(0);
        rbtn1.setSelected(false);
        rbtn2.setSelected(false);
        pw.setText("");
        cpw.setText("");
        
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DoctorLoginView d1 = new DoctorLoginView();
        d1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn1ActionPerformed
        
    }//GEN-LAST:event_rbtn1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        loginHome a1 = new loginHome();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorRegistraionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorRegistraionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorRegistraionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorRegistraionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorRegistraionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup availabilitygroup;
    private javax.swing.JComboBox<String> boxSpc;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btncreate;
    private javax.swing.JCheckBox chkbox1;
    private javax.swing.JCheckBox chkbox2;
    private javax.swing.JPasswordField cpw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pw;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
